apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-microservice
  labels:
    app: home-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: home-app
  template:
    metadata:
      labels:
        app: home-app
    spec:
      containers:
        - name: home-app
          image: vietaws/eks:home
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: home-nodeport-service
  labels:
    app: home-app
spec:
  type: NodePort
  selector:
    app: home-app
  ports:
    - port: 8080
      targetPort: 8080
      #nodePort: 31988
